"""Features defined by soliplex"""

import pydantic
from haiku.rag.agents.chat import state as hr_chat_state

HAIKU_CHAT_FEATURE = hr_chat_state.AGUI_STATE_KEY

# ------------------------------------------------------------------
#  filter_documents
# ------------------------------------------------------------------

FILTER_DOCUMENTS_FEATURE = "filter_documents"


class FilterDocuments(pydantic.BaseModel):
    """Documents selected by the user to filter answers

    This model describes the 'filter_documents' key in the
    AG-UI state.

    If 'document_ids' is empty or None, or if the
    'filter_documents' key is not present in the AG-UI state,
    no filter is applied: the 'ask_with_rich_citations' tool
    will return all documents matching the query from the LLM.
    """

    document_ids: list[str] | None = None


# ------------------------------------------------------------------
#  ask_history
# ------------------------------------------------------------------

ASK_HISTORY_FEATURE = "ask_history"


class QuestionResponseCitations(pydantic.BaseModel):
    """Single question/response from 'ask_with_rich_citations'

    Includes response generated by the tool and accompanying
    citations.
    """

    question: str
    response: str
    citations: list[hr_chat_state.Citation] = []


class AskedAndAnswered(pydantic.BaseModel):
    """History of questions asked and their replies + citations

    This model describes the 'ask_history' key in the AG-UI
    state.

    Each call to the 'ask_with_rich_citations' tool appends
    one entry to the 'questions' list.
    """

    questions: list[QuestionResponseCitations] = []


# ------------------------------------------------------------------
#  monty
# ------------------------------------------------------------------

MONTY_FEATURE = "monty"


class MontyState(pydantic.BaseModel):
    """State for the monty room

    This model describes the 'monty' key in the AG-UI state,
    carrying context passed through the monty bridge.
    """

    ace_skillbook_context: str = ""
