// GENERATED by scripts/generate_dart_views.py — DO NOT EDIT.
import 'package:meta/meta.dart';

/// History of questions asked and their replies + citations
///
/// This model describes the 'ask_history' key in the AG-UI
/// state.
///
/// Each call to the 'ask_with_rich_citations' tool appends
/// one entry to the 'questions' list.
@immutable
class AskHistoryView {
  const AskHistoryView(this._data);
  final Map<String, dynamic> _data;

  List<Map<String, dynamic>> get questionsRaw =>
      (_data['questions'] as List<dynamic>?)
          ?.cast<Map<String, dynamic>>() ??
          const [];

  int get questionsLength =>
      (_data['questions'] as List<dynamic>?)?.length ?? 0;

  List<QuestionResponseCitationsView> get questions =>
      questionsRaw.map(QuestionResponseCitationsView.new).toList();
}

/// Single question/response from 'ask_with_rich_citations'
///
/// Includes response generated by the tool and accompanying
/// citations.
@immutable
class QuestionResponseCitationsView {
  const QuestionResponseCitationsView(this._data);
  final Map<String, dynamic> _data;

  String get question =>
      _data['question'] as String? ?? '';

  String get response =>
      _data['response'] as String? ?? '';

  List<Map<String, dynamic>> get citationsRaw =>
      (_data['citations'] as List<dynamic>?)
          ?.cast<Map<String, dynamic>>() ??
          const [];

  int get citationsLength =>
      (_data['citations'] as List<dynamic>?)?.length ?? 0;

  List<CitationView> get citations =>
      citationsRaw.map(CitationView.new).toList();
}

/// Resolved citation with full metadata for display/visual grounding.
///
/// Used by both research graph and chat agent. The optional index field
/// supports UI display ordering in chat contexts.
@immutable
class CitationView {
  const CitationView(this._data);
  final Map<String, dynamic> _data;

  int? get index =>
      _data['index'] as int?;

  String get documentId =>
      _data['document_id'] as String? ?? '';

  String get chunkId =>
      _data['chunk_id'] as String? ?? '';

  String get documentUri =>
      _data['document_uri'] as String? ?? '';

  String? get documentTitle =>
      _data['document_title'] as String?;

  List<int> get pageNumbers =>
      (_data['page_numbers'] as List<dynamic>?)
          ?.cast<int>() ?? const [];

  List<String>? get headings =>
      (_data['headings'] as List<dynamic>?)
          ?.cast<String>();

  String get content =>
      _data['content'] as String? ?? '';
}
