// GENERATED by scripts/generate_dart_views.py — DO NOT EDIT.
import 'package:meta/meta.dart';

/// Documents selected by the user to filter answers
///
/// This model describes the 'filter_documents' key in the
/// AG-UI state.
///
/// If 'document_ids' is empty or None, or if the
/// 'filter_documents' key is not present in the AG-UI state,
/// no filter is applied: the 'ask_with_rich_citations' tool
/// will return all documents matching the query from the LLM.
@immutable
class FilterDocumentsView {
  const FilterDocumentsView(this._data);
  final Map<String, dynamic> _data;

  List<String>? get documentIds =>
      (_data['document_ids'] as List<dynamic>?)
          ?.cast<String>();
}
