// GENERATED by scripts/generate_dart_views.py — DO NOT EDIT.
import 'package:meta/meta.dart';

/// State shared between frontend and agent via AG-UI.
@immutable
class HaikuRagChatView {
  const HaikuRagChatView(this._data);
  final Map<String, dynamic> _data;

  String? get initialContext =>
      _data['initial_context'] as String?;

  List<Map<String, dynamic>> get citationsRaw =>
      (_data['citations'] as List<dynamic>?)
          ?.cast<Map<String, dynamic>>() ??
          const [];

  int get citationsLength =>
      (_data['citations'] as List<dynamic>?)?.length ?? 0;

  List<CitationView> get citations =>
      citationsRaw.map(CitationView.new).toList();

  List<dynamic> get citationsHistory =>
      (_data['citations_history'] as List<dynamic>?) ?? const [];

  int get citationsHistoryLength =>
      (_data['citations_history'] as List<dynamic>?)?.length ?? 0;

  List<Map<String, dynamic>> get qaHistoryRaw =>
      (_data['qa_history'] as List<dynamic>?)
          ?.cast<Map<String, dynamic>>() ??
          const [];

  int get qaHistoryLength =>
      (_data['qa_history'] as List<dynamic>?)?.length ?? 0;

  List<QAHistoryEntryView> get qaHistory =>
      qaHistoryRaw.map(QAHistoryEntryView.new).toList();

  SessionContextView? get sessionContext {
    final raw = _data['session_context'];
    if (raw == null) return null;
    return SessionContextView(
      raw as Map<String, dynamic>,
    );
  }

  List<String> get documentFilter =>
      (_data['document_filter'] as List<dynamic>?)
          ?.cast<String>() ?? const [];

  Map<String, int> get citationRegistry =>
      (_data['citation_registry'] as Map<String, dynamic>?)
          ?.cast<String, int>() ?? const {};
}

/// Resolved citation with full metadata for display/visual grounding.
///
/// Used by both research graph and chat agent. The optional index field
/// supports UI display ordering in chat contexts.
@immutable
class CitationView {
  const CitationView(this._data);
  final Map<String, dynamic> _data;

  int? get index =>
      _data['index'] as int?;

  String get documentId =>
      _data['document_id'] as String? ?? '';

  String get chunkId =>
      _data['chunk_id'] as String? ?? '';

  String get documentUri =>
      _data['document_uri'] as String? ?? '';

  String? get documentTitle =>
      _data['document_title'] as String?;

  List<int> get pageNumbers =>
      (_data['page_numbers'] as List<dynamic>?)
          ?.cast<int>() ?? const [];

  List<String>? get headings =>
      (_data['headings'] as List<dynamic>?)
          ?.cast<String>();

  String get content =>
      _data['content'] as String? ?? '';
}

/// A Q&A pair with optional cached embedding for similarity matching.
@immutable
class QAHistoryEntryView {
  const QAHistoryEntryView(this._data);
  final Map<String, dynamic> _data;

  String get question =>
      _data['question'] as String? ?? '';

  String get answer =>
      _data['answer'] as String? ?? '';

  double get confidence =>
      (_data['confidence'] as num?)?.toDouble() ?? 0.9;

  List<Map<String, dynamic>> get citationsRaw =>
      (_data['citations'] as List<dynamic>?)
          ?.cast<Map<String, dynamic>>() ??
          const [];

  int get citationsLength =>
      (_data['citations'] as List<dynamic>?)?.length ?? 0;

  List<CitationView> get citations =>
      citationsRaw.map(CitationView.new).toList();

  List<double>? get questionEmbedding =>
      (_data['question_embedding'] as List<dynamic>?)
          ?.map((e) => (e as num).toDouble())
          .toList();
}

/// Compressed summary of conversation history for research graph.
@immutable
class SessionContextView {
  const SessionContextView(this._data);
  final Map<String, dynamic> _data;

  String get summary =>
      _data['summary'] as String? ?? '';

  String? get lastUpdated =>
      _data['last_updated'] as String?;
}
