// GENERATED by scripts/generate_dart_views.py — DO NOT EDIT.
import 'package:meta/meta.dart';

/// State for the monty room
///
/// This model describes the 'monty' key in the AG-UI state,
/// carrying context passed through the monty bridge.
@immutable
class MontyView {
  const MontyView(this._data);
  final Map<String, dynamic> _data;

  String get aceSkillbookContext =>
      _data['ace_skillbook_context'] as String? ?? '';
}
